version: '3.3'
services:
  watchtower:
    container_name: watchtower
    restart: always
    environment:
      - TZ=Europe/London
      - WATCHTOWER_LIFECYCLE_HOOKS=1
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://1724826386:AAGeFEhps8_0H1vJLOxa9Yy8i3Fr5XZ30Gk@telegram/?channels=373334037
    command: --interval 30 nginx node-red swagger-ui
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    image: containrrr/watchtower

  nginx:
    image: kunilee/nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"

  node-red:
    image: kunilee/node-red:latest
    container_name: node-red
    depends_on:
      - mysql
    restart: always
    ports:
      - "1880:1880"
    tty: true
    environment:
      TZ: ${TZ}
      MYSQL_IP: ${MYSQL_IP_ENV}
    volumes:
      - settings:/data/context/global

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./dbdata:/var/lib/mysql/

  adminer:
    image: adminer
    depends_on:
      - mysql
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pappu687
      ADMINER_DEFAULT_SERVER: mysql

  swagger-ui:
    image: kunilee/swagger-ui:latest
    restart: always
    container_name: swagger-ui
    ports:
      - 8000:8080